import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>): JSX.Element {
	return (
		<html lang="en">
			<body className={inter.className}>
				<main className="my-12 flex w-full">{children}</main>
				<footer className="w-full bg-gray-100 p-16 text-center">
					<p className="font-bold">NEXTJS 14 MASTERS</p>
				</footer>
			</body>
		</html>
	);
}
